language: go
sudo: false
addons:
  apt:
    packages:
      - openssl
      - gnutls-bin
      - libnss3-tools

install:
  - go get github.com/google/der-ascii/...
  - go install github.com/google/der-ascii/cmd/ascii2der
  - go install github.com/google/der-ascii/cmd/der2ascii
script:
  - make bin/gox509
  - make
