language: go
sudo: false
addons:
  apt:
    packages:
      - openssl
      - gnutls-bin
      - libnss3-tools

install:
  - go get github.com/google/der-ascii/cmd/ascii2der
  - go get github.com/google/der-ascii/cmd/der2ascii
  - go get github.com/google/certificate-transparency-go/x509util/certcheck
script:
  - make bin/gox509
  - make
